
// Creation of action types. 

const SET_DRAWER = "SET_DRAWER";
const ADD_MESSAGE = "ADD_MESSAGE"; 
const DELETE_MESSAGE = "DELETE_MESSAGE";
const ADD_USER = "ADD_USER";
const DELETE_CARD = "DELETE_USER";
const GUESS_INPUT = "GUESS_INPUT"; 

export {
	SET_DRAWER,
	ADD_MESSAGE, 
	DELETE_MESSAGE,
	ADD_USER,
	DELETE_CARD,
	GUESS_INPUT
}