
// Creation of action types.

const SET_DRAWER = "SET_DRAWER";
const GET_USERS = "GET_USERS";
const SET_GUESS_INPUT = "SET_GUESS_INPUT";
const SEND_GUESS = "SEND_GUESS";
const ADD_MESSAGE = "ADD_MESSAGE";


export {
	SET_DRAWER,
	ADD_MESSAGE,
	GET_USERS,
	SET_GUESS_INPUT,
	SEND_GUESS
}
