
// Creation of action types.

const SET_DRAWER = "SET_DRAWER";
const GET_USERS = "GET_USERS";
const SET_GUESS_INPUT = "SET_GUESS_INPUT";
const SEND_GUESS = "SEND_GUESS";
const ADD_MESSAGE = "ADD_MESSAGE";
const ADD_CLICK = "ADD_CLICK";
const ADD_PIXS = "ADD_PIXS";
const SET_ID = 'SET_ID';
const CLEAR_CANVAS = "CLEAR_CANVAS";


export {
	SET_DRAWER,
	SET_ID,
	GET_USERS,
	ADD_MESSAGE,
	SET_GUESS_INPUT,
	SEND_GUESS,
	ADD_CLICK,
	ADD_PIXS,
	CLEAR_CANVAS,
}
